version: '3.8'

services:
  server:
    build:
      context: .
    hostname: pow-server
    env_file:
      - .env.example
    expose:
      - 9000
    ports:
      - "${SERVER_PORT}:9000"
    networks:
      - pow-network
    command: ["python", "-m", "src.cmd.server"]

  client:
    build:
      context: .
    depends_on:
      - server
    restart: unless-stopped
    env_file:
      - .env.example
    environment:
      - SERVER_HOST=pow-server
    networks:
      - pow-network
    command: ["python", "-m", "src.cmd.client"]

networks:
  pow-network: {}
